### ISSUE TITLE
Switch to https

### ISSUE THREAD

**Issue by Schnark** [js13kGames/js13kgames.com-legacy#3]
Currently js13kgames.com uses http. As far as I can see, https is actually available, but only with a self-signed certificate, so it currently requires some manual fiddling to load the site via a secure connection.
Since Chrome (and possibly other browser vendors) plan to remove some web APIs from insecure content, it sooner or later is necessary to load the games via https to make them playable: Among others, https://bugs.chromium.org/p/chromium/issues/detail?id=520765 lists Fullscreen API and Devicemotion for removal. There seems to be no timeframe yet, but once they actually remove these APIs, https is more or less mandatory.
So this isn't an urgent issue, but something to be done eventually.

**Comment by end3r** [comment]
Yes, the new backend will have https thanks to Let's Encrypt, but I might be able to turn it on even sooner.
